version: '3.5'
services:

  nginx:
    container_name: nginx
    build: nginx-container/.
    ports:
      - '8080:80'


  app_a:
    container_name: app_a
    build: appA/.
    volumes:
      - /home/cedrick/NodeJsProjects/docker_arch/appA:/usr/src/app
    ports:
      - '8081:3000'
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /var/lib/docker/volumes/mongodbdata:/data/db
    ports:
      - '27017:27017'
